### PR TITLE
FPST1.0

### PR DESCRIPTION
**Pull request by SashaPankov**

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for sending your project for review, it already looks decent! I marked several small issues below and hope that theu can help you to improve your project and get more final points. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * background image shouldn't disappear and header of the `home` page shouldn't change its theme when the person is logged in. Header theme depends on the page - dark version of the `home` page and light version of the `savednews` page
    * Mismatches of the main page on 1440px https://pasteboard.co/Rlocai5mGv7n.png
    * Mismatches of the main page on 768px https://pasteboard.co/C9hxSdn1HvGw.png https://pasteboard.co/QDrturZNbMsW.png https://pasteboard.co/kuc4JOjYq61D.png
    * Mismatches of the main page on 320px https://pasteboard.co/ncFtYjbHawp8.png https://pasteboard.co/75cwXA76JgfX.png
    * `savednews` page looks different from the mockup on 768 viewport
    * Modal window doesn't look similar with the mockup on all screen resolutions - please check all sizes, spaces and text properties (and please make sure that close button is visible)
    * Modal input error looks different from the mockup
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page scrolls horizontally on 321px - 700px, 769px - 1187px screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * You can use modifiers, but `signedin` modifier should be key-value modifier
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * You should use `main`, `footer` and `section` tags in the project in proper places
    * `search__title`, `about__title`, `savednewsheader__title`, `newscard__title` should be marked with heading tag
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * Project has several eslint errors and warnings

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * All buttons should have hover states (and clicked/active states where necessary) according to the mockup
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * All `font-family` styles should have alternative fonts
- [ ]  Images have an `alt` attribute containing appropriate values.
    * Not all `img` tags have `alt` attributes
- [x]  Raster and vector images have been optimized.

## Number of points: 57

**Comment by SashaPankov** [comment]
Thank you for review and summary. Tried to fix as much as I can. Supporting responsibility is very time consuming.

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for the corrections, your project looks better! Several small issues below are left:⏬

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
     * Modal window doesn't look similar with the mockup on 320 viewport - please check all sizes, spaces and text properties. Also modal window should have bigher height and should be centered vertically
     * Mismatches of the savednews page on 320 viewport https://pasteboard.co/fAecRTyQ2oHu.png and 1440 viewport https://pasteboard.co/7DXeeKARFwt8.png
     * Footer links should look different according to the mockup
     * Incorrect text properties of `news__caption` on 768 viewport
     * Mismatches of the main page on 320 viewport https://pasteboard.co/Hgv6aEdcpez1.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * There's a very big space between the news cards and more  button on 1232px - 1245px screen resolutions
    * The main page should keep its layout on more than 1440px screen resolutions - all page content should be centered horizontally and shouldn't extend outside their sections
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Search form button should have active state
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * All `font-family` styles should have alternative fonts
- [ ]  Images have an `alt` attribute containing appropriate values.
    * Not all img tags have `alt` attributes
- [x]  Raster and vector images have been optimized.

## Number of points: 69

Good luck!✨

**Comment by FiLLa-FaS** [comment]
Hello! You've got more than 80 points, so I'm glad to accept your project now. You can fix the rest small issue to improve your project a little bit more. Good luck on the next stage!🥷🚀

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The main page should keep its layout on more than 1440px screen resolutions - all page content should be centered horizontally and shouldn't extend outside their sections. Note, that width of the page content shouldn't be changed on more tha 1440px screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 87

**Pull request merged**
